### ISSUE TITLE
Gradle sync failed

### ISSUE THREAD

**Issue by MagicValots** [manojbhadane/QButton#2]
Hi, i want to try your library but i can't sync gradle, after imported mavel jitpack and the implementation i've received the classic error:

> ERROR: Failed to resolve: com.github.manojbhadane:QButton:v1.1
> Affected Modules: app

I've also tried with 1.0 version, same result.

**Comment by manojbhadane** [comment]
Add this line in project level gradle in allprojects section 
`maven { url 'https://jitpack.io' }`

Like

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by manojbhadane** [comment]
> Hi, i want to try your library but i can't sync gradle, after imported mavel jitpack and the implementation i've received the classic error:
> 
> > ERROR: Failed to resolve: com.github.manojbhadane:QButton:v1.1
> > Affected Modules: app
> 
> I've also tried with 1.0 version, same result.



> Hi, i want to try your library but i can't sync gradle, after imported mavel jitpack and the implementation i've received the classic error:
> 
> > ERROR: Failed to resolve: com.github.manojbhadane:QButton:v1.1
> > Affected Modules: app
> 
> I've also tried with 1.0 version, same result.

Add this line in project level gradle in allprojects section
`maven { url 'https://jitpack.io' }`

Like

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by MagicValots** [comment]
Yes i've added all, maven inside .gradle all projecs,  and the library inside .gradle project.... like other libraries.... maybe some problem with Android version? 

My configuration:

> minSdkVersion 19
        targetSdkVersion 28

But it's impossible you are using AppCompatButton....

Maybe there is a conflict with other libraries, i use:

> implementation 'com.github.bassaer:materialdesigncolors:1.0.0'
    implementation 'com.github.markushi:circlebutton:1.1'
    implementation 'com.github.medyo:fancybuttons:1.9.0'

**Comment by manojbhadane** [comment]
> Yes i've added all, maven inside .gradle all projecs, and the library inside .gradle project.... like other libraries.... maybe some problem with Android version?
> 
> My configuration:
> 
> > minSdkVersion 19
> > targetSdkVersion 28
> 
> But it's impossible you are using AppCompatButton....
> 
> Maybe there is a conflict with other libraries, i use:
> 
> > implementation 'com.github.bassaer:materialdesigncolors:1.0.0'
> > implementation 'com.github.markushi:circlebutton:1.1'
> > implementation 'com.github.medyo:fancybuttons:1.9.0'

Can you please post your project level build.gradle file

**Comment by MagicValots** [comment]
```
 buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}
```

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by MagicValots** [comment]
Perfect now with version 1.2 works correctly! what was the problem?

**Comment by manojbhadane** [comment]
> Perfect now with version 1.2 works correctly! what have you changed?

👍 

Some changes related to version
