### ISSUE TITLE
Disable state

### ISSUE THREAD

**Issue by MagicValots** [manojbhadane/QButton#3]
Hi, i'm here again.

Can you consider to add a disable state to the button? maybe when the user disable it you can set an alpha or add a mask color.

**Comment by manojbhadane** [comment]
> Hi, i'm here again.
> 
> Can you consider to add a disable state to the button? maybe when the user disable it you can set an alpha or add a mask color.

Sure.. will try to add it ASAP

**Comment by manojbhadane** [comment]
Version v1.3 updated with above feature.. please check

`implementation 'com.github.manojbhadane:QButton:v1.3'`

Just use `android:enabled="true or false"`

**Comment by nikitoSha** [comment]
> 
> 
> Version `v1.3` updated with above feature.. please check
> 
> `implementation 'com.github.manojbhadane:QButton:v1.3'`
> 
> Just use `android:enabled="true or false"`

Hi! Thanks, good lib.
I have a problem: If we set enabled = false and fast change this value to false, then button change color (like disabled) and we can click on it (clickable). How to update button state after fast changing "enabled"?

**Comment by nikitoSha** [comment]
.invalidate() not helps me

**Comment by nikitoSha** [comment]
Ohh, man. Why are you doing only 0.6 alpha?
Why not "else" and set setAlpha(1f);?

**Comment by nikitoSha** [comment]
For those, who have this problem, the fast way to resolve is:
```
cancelTask_btn.setEnabled(true);
cancelTask_btn.setAlpha(1f);
```
